[2023-04-26T10:11:56.951+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag2.send_email_task scheduled__2023-04-25T00:00:00+00:00 [queued]>
[2023-04-26T10:11:56.958+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag2.send_email_task scheduled__2023-04-25T00:00:00+00:00 [queued]>
[2023-04-26T10:11:56.959+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T10:11:56.959+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-04-26T10:11:56.959+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T10:11:56.974+0000] {taskinstance.py:1383} INFO - Executing <Task(EmailOperator): send_email_task> on 2023-04-25 00:00:00+00:00
[2023-04-26T10:11:56.980+0000] {standard_task_runner.py:55} INFO - Started process 4377 to run task
[2023-04-26T10:11:56.984+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag2', 'send_email_task', 'scheduled__2023-04-25T00:00:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmp89zfo2_e']
[2023-04-26T10:11:56.985+0000] {standard_task_runner.py:83} INFO - Job 254: Subtask send_email_task
[2023-04-26T10:11:57.042+0000] {task_command.py:376} INFO - Running <TaskInstance: dag2.send_email_task scheduled__2023-04-25T00:00:00+00:00 [running]> on host c452347a64f2
[2023-04-26T10:11:57.094+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag2
AIRFLOW_CTX_TASK_ID=send_email_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-25T00:00:00+00:00
[2023-04-26T10:11:57.104+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-04-26T10:11:57.105+0000] {configuration.py:569} WARNING - section/key [smtp/smtp_user] not found in config
[2023-04-26T10:11:57.105+0000] {email.py:229} INFO - Email alerting: attempt 1
[2023-04-26T10:11:57.107+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-04-26T10:11:57.116+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dag2, task_id=send_email_task, execution_date=20230425T000000, start_date=20230426T101156, end_date=20230426T101157
[2023-04-26T10:11:57.123+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 254 for task send_email_task ([Errno 99] Cannot assign requested address; 4377)
[2023-04-26T10:11:57.155+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-04-26T10:11:57.174+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
