[2023-04-26T06:29:13.317+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.copy_task manual__2023-04-26T06:29:08.360875+00:00 [queued]>
[2023-04-26T06:29:13.324+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.copy_task manual__2023-04-26T06:29:08.360875+00:00 [queued]>
[2023-04-26T06:29:13.325+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T06:29:13.325+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-04-26T06:29:13.326+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T06:29:13.334+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): copy_task> on 2023-04-26 06:29:08.360875+00:00
[2023-04-26T06:29:13.341+0000] {standard_task_runner.py:55} INFO - Started process 333 to run task
[2023-04-26T06:29:13.345+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'copy_task', 'manual__2023-04-26T06:29:08.360875+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpg180f9qv']
[2023-04-26T06:29:13.347+0000] {standard_task_runner.py:83} INFO - Job 183: Subtask copy_task
[2023-04-26T06:29:13.401+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.copy_task manual__2023-04-26T06:29:08.360875+00:00 [running]> on host b0d118a97f46
[2023-04-26T06:29:13.450+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=copy_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T06:29:08.360875+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T06:29:08.360875+00:00
[2023-04-26T06:29:13.459+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-04-26T06:29:13.466+0000] {sql.py:315} INFO - Running statement: COPY users FROM '/tmp/processed_user.csv' WITH (FORMAT CSV, HEADER FALSE);, parameters: None
[2023-04-26T06:29:13.467+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 40, in copy_csv_to_postgres
    pg_hook.run(copy_sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/tmp/processed_user.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-04-26T06:29:13.477+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=copy_task, execution_date=20230426T062908, start_date=20230426T062913, end_date=20230426T062913
[2023-04-26T06:29:13.484+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 183 for task copy_task (could not open file "/tmp/processed_user.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 333)
[2023-04-26T06:29:13.517+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-04-26T06:29:13.536+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
