[2023-04-26T10:52:50.798+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag2.send_email_task manual__2023-04-26T10:52:48.314010+00:00 [queued]>
[2023-04-26T10:52:50.804+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag2.send_email_task manual__2023-04-26T10:52:48.314010+00:00 [queued]>
[2023-04-26T10:52:50.804+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T10:52:50.805+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-04-26T10:52:50.805+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T10:52:50.813+0000] {taskinstance.py:1383} INFO - Executing <Task(EmailOperator): send_email_task> on 2023-04-26 10:52:48.314010+00:00
[2023-04-26T10:52:50.818+0000] {standard_task_runner.py:55} INFO - Started process 125 to run task
[2023-04-26T10:52:50.822+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag2', 'send_email_task', 'manual__2023-04-26T10:52:48.314010+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpae3c9j64']
[2023-04-26T10:52:50.823+0000] {standard_task_runner.py:83} INFO - Job 261: Subtask send_email_task
[2023-04-26T10:52:50.880+0000] {task_command.py:376} INFO - Running <TaskInstance: dag2.send_email_task manual__2023-04-26T10:52:48.314010+00:00 [running]> on host 641cb7472cb1
[2023-04-26T10:52:50.936+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag2
AIRFLOW_CTX_TASK_ID=send_email_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T10:52:48.314010+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T10:52:48.314010+00:00
[2023-04-26T10:52:50.945+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-04-26T10:52:50.946+0000] {email.py:229} INFO - Email alerting: attempt 1
[2023-04-26T10:52:53.135+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 240, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/local/lib/python3.7/smtplib.py", line 735, in login
    raise last_exception
  File "/usr/local/lib/python3.7/smtplib.py", line 726, in login
    initial_response_ok=initial_response_ok)
  File "/usr/local/lib/python3.7/smtplib.py", line 647, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials c4-20020aa78804000000b0062e00158bf4sm10935871pfo.208 - gsmtp')
[2023-04-26T10:52:53.167+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dag2, task_id=send_email_task, execution_date=20230426T105248, start_date=20230426T105250, end_date=20230426T105253
[2023-04-26T10:52:53.184+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 261 for task send_email_task ((535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials c4-20020aa78804000000b0062e00158bf4sm10935871pfo.208 - gsmtp'); 125)
[2023-04-26T10:52:53.238+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-04-26T10:52:53.254+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
